### ISSUE TITLE
java.lang.NoSuchMethodError crash

### ISSUE THREAD

**Issue by NancalaStarry** [TeamGensouSpark/Grimoire-of-Patchouli#1]
[crash-2023-10-23_18.35.04-client.txt](https://github.com/TeamGensouSpark/Grimoire-of-Patchouli/files/13069212/crash-2023-10-23_18.35.04-client.txt)

**Comment by H2Sxxa** [comment]
`1.2.1`版本的Kekkai请使用`Actions`里的版本，`1.2.0`升`1.2.1`时候做了些许改动，或者你可以尝试使用`1.2.0`的Kekkai

更推荐使用`Actions`里的最新版~

**Comment by NancalaStarry** [comment]
嗯呐，现在尝试一下

**Comment by NancalaStarry** [comment]
解决了，谢谢w祝你有美好的一天w
